### ISSUE TITLE
lubuntu-updater stucks on SDDM update prompt

### ISSUE THREAD

**Issue by Lukaszeq** [lubuntu-team/lubuntu-update-notifier#5]
I suppose the updater does not allow any interactivity from update scripts. I have stumbled upon a problem with SDDM.

The upgrader prints `Setting up sddm (0.19.0-2ubuntu2.2) ...` and then it waits for a keystroke. However, when I update SDDM via apt everything is in order, like so:
```
Setting up sddm (0.19.0-2ubuntu2.2) ...

Configuration file '/usr/share/sddm/scripts/Xsetup'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** Xsetup (Y/I/N/O/D/Z) [default=N] ? y
```

The updater omits the action prompt, therefore it is impossible to proceed with the update.

**Comment by monetaryabyss** [comment]
This bug has been [reported on launchpad](https://bugs.launchpad.net/ubuntu/+source/lubuntu-update-notifier/+bug/1998937). Please comment and follow there.

**Comment by tsimonq2** [comment]
Solved a little while ago.
